module_bedrock_configuration:
  path: /kjmodulebedrock/configuration
  methods: [GET]
  defaults:
    _controller: 'Kaudaj\Module\ModuleBedrock\Controller\Admin\ConfigurationController::indexAction'
    _legacy_controller: ModuleBedrockConfiguration

module_bedrock_configuration_preferences_save:
  path: /kjmodulebedrock/configuration/preferences
  methods: [POST, PATCH]
  defaults:
    _controller: 'Kaudaj\Module\ModuleBedrock\Controller\Admin\ConfigurationController::processPreferencesFormAction'
    _legacy_controller: ModuleBedrockConfiguration
    _legacy_link: ModuleBedrockConfiguration:update