services:
  _defaults:
    public: true

  kaudaj.modulebedrock.form.type.module_bedrock_configuration_type:
    class: 'Kaudaj\Module\ModuleBedrock\Form\ModuleBedrockConfigurationType'
    parent: 'form.type.translatable.aware'
    public: true
    tags:
      - { name: form.type }

  kaudaj.module.modulebedrock.form.module_bedrock_configuration_form_data_provider:
    class: 'Kaudaj\Module\ModuleBedrock\Form\ModuleBedrockConfigurationFormDataProvider'
    arguments:
      - '@kaudaj.module.modulebedrock.form.module_bedrock_configuration'

  kaudaj.module.modulebedrock.form.module_bedrock_configuration_form_data_handler:
    class: 'PrestaShop\PrestaShop\Core\Form\Handler'
    arguments:
      - '@form.factory'
      - '@prestashop.core.hook.dispatcher'
      - '@kaudaj.module.modulebedrock.form.module_bedrock_configuration_form_data_provider'
      - 'Kaudaj\Module\ModuleBedrock\Form\ModuleBedrockConfigurationType'
      - 'ModuleBedrockConfiguration'

  kaudaj.module.modulebedrock.form.module_bedrock_configuration:
    class: Kaudaj\Module\ModuleBedrock\Form\ModuleBedrockConfiguration
    arguments:
      - '@prestashop.adapter.legacy.configuration'
      - '@prestashop.adapter.shop.context'
      - '@prestashop.adapter.multistore_feature'
